// Generated by ts-to-zod
import { z } from "zod";
import { Json } from "./database.types";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const treatmentTemplatesRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.string(),
  procedures: jsonSchema,
  symptom: z.string(),
});

export const treatmentTemplatesInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  procedures: jsonSchema,
  symptom: z.string(),
});

export const treatmentTemplatesUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  procedures: jsonSchema.optional(),
  symptom: z.string().optional(),
});

export const treatmentTemplatesRelationshipsSchema = z.tuple([]);

export const treatmentsRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.string(),
  label: z.string(),
  procedures: jsonSchema.nullable(),
  symptom: z.string(),
  treatment_finished_at: z.string().nullable(),
  treatment_started_at: z.string().nullable(),
});

export const treatmentsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  label: z.string(),
  procedures: jsonSchema.optional().nullable(),
  symptom: z.string(),
  treatment_finished_at: z.string().optional().nullable(),
  treatment_started_at: z.string().optional().nullable(),
});

export const treatmentsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  label: z.string().optional(),
  procedures: jsonSchema.optional().nullable(),
  symptom: z.string().optional(),
  treatment_finished_at: z.string().optional().nullable(),
  treatment_started_at: z.string().optional().nullable(),
});

export const treatmentsRelationshipsSchema = z.tuple([]);
